messages:
  ignored_pack:
    enabled: true
    message: "&6Skipped resourcepack installation (you already loaded it)."
equal_pack_attributes:
  hash: true
  forced: true
  prompt_message: true
ignore_hash_in_url: true
main_spigot_server_name: server_1
ignored_servers:
  - ignored_1
  - ignored_2
log:
  ignored_respack: false
  sent_respack: false
  debug: false